# =================================================================
# ZEGA TOOLCHAIN SETUP - VERSION 2.0.0.4 STABLE
# Global Persistent Controller with Scaffolding Support
# =================================================================

# 1. ENVIRONMENT CONFIGURATION
$global:ZegaRoot     = "D:\temporary\Z#"
$global:BinRoot      = Join-Path $global:ZegaRoot "bin"
$global:CompilerExe  = Join-Path $global:BinRoot "compiler\zscomp.exe"
$global:RuntimeExe   = Join-Path $global:BinRoot "runtime\zsruntime.exe"
$global:VersionFile  = Join-Path $global:ZegaRoot "version.json"

# ANSI Branding: #58f01b
$global:ZEGA_CLR = "`e[38;2;88;240;27m"
$global:RESET    = "`e[0m"

# 2. INTERNAL UTILITIES

function global:Write-Status {
    param([string]$Message, [string]$Type = "INFO")
    switch ($Type) {
        "ERROR"   { Write-Host "[!] $Message" -ForegroundColor Red }
        "SUCCESS" { Write-Host "${global:ZEGA_CLR}[+] $Message${global:RESET}" }
        "WARN"    { Write-Host "[?] $Message" -ForegroundColor Yellow }
        default   { Write-Host "[*] $Message" -ForegroundColor Cyan }
    }
}

function global:Invoke-NewProject {
    param([string]$Name)
    $Path = Join-Path $PWD $Name
    if (Test-Path $Path) {
        Write-Status "Project folder '$Name' already exists!" "ERROR"
        return
    }

    Write-Status "Scaffolding new ZEGA project: $Name" "INFO"
    New-Item -ItemType Directory -Path $Path | Out-Null

    # Create main.zs template
    $ZSContent = @"
~ ZEGA Application: $Name
~ Generated by ZEGA Forge 2.0.0.4

win_title{$Name}
win_w{1280}
win_h{720}
fps{60}

print{Starting $Name...}
print{Initializing UI Components...}

~ UI Layout: Button at center
win_button{new *{540, 310}* *{200, 100}*}

boot{}
"@
    $ZSPath = Join-Path $Path "main.zs"
    $ZSContent | Out-File -FilePath $ZSPath -Encoding utf8

    # Create version.json template
    $JSONContent = @"
{
    "engine_name": "Z#",
    "project_name": "$Name",
    "version": "1.0.0",
    "build_type": "Alpha",
    "owner": "ZEGA"
}
"@
    $JSONPath = Join-Path $Path "version.json"
    $JSONContent | Out-File -FilePath $JSONPath -Encoding utf8

    Write-Status "Project '$Name' is ready for Forge ignition." "SUCCESS"
    Write-Status "Path: $Path" "INFO"
}

# 3. THE GLOBAL DISPATCHER

function global:zs {
    [CmdletBinding()]
    param(
        [Parameter(Position = 0)]
        [string]$FirstArg,

        [Parameter(ValueFromRemainingArguments = $true)]
        [string[]]$Rest
    )

    # --new logic (Detects --new --name)
    if ($FirstArg -eq '--new') {
        $projectName = $null
        foreach ($arg in $Rest) {
            if ($arg.StartsWith("--")) {
                $projectName = $arg.Substring(2)
                break
            }
        }

        if (-not $projectName) {
            Write-Status "Usage: zs --new --<project_name>" "ERROR"
            return
        }
        Invoke-NewProject -Name $projectName
        return
    }

    # Standard Flags
    if ($FirstArg -in '--v', '-v', '--version') {
        if (Test-Path "version.json") {
            $Data = Get-Content "version.json" | ConvertFrom-Json
            Write-Host "`n${global:ZEGA_CLR}--- PROJECT STATUS ---"
            Write-Host "Project: $($Data.project_name)"
            Write-Host "Version: $($Data.version)"
            Write-Host "Owner:   $($Data.owner)"
            Write-Host "-----------------------${global:RESET}`n"
        } else {
            Write-Host "${global:ZEGA_CLR}ZEGA Global Runtime v2.0.0.4 Ready${global:RESET}"
        }
        return
    }
    
    if ($FirstArg -in '--help', '-h') {
        Write-Host "`n${global:ZEGA_CLR}ZEGA Z# CLI v2.0.0.4${global:RESET}"
        Write-Host "  zs --new --<name>  Create a new project folder"
        Write-Host "  zs --clean         Purge all .zsef files"
        Write-Host "  zs --compile <f>   Forge .zs into .zsef"
        Write-Host "  zs --run <f>       Ignite .zsef bytecode"
        return
    }

    if ($FirstArg -eq '--clean') { 
        Write-Status "Cleaning bytecode..." "INFO"
        Get-ChildItem -Filter *.zsef -Recurse | Remove-Item -Force
        Write-Status "Registry clean." "SUCCESS"
        return 
    }

    # Command: --compile
    if ($FirstArg -eq '--compile') {
        $file = $Rest[0]
        if (-not $file -or -not (Test-Path $file)) { Write-Status "File not found." "ERROR"; return }
        & $global:CompilerExe $file
        return
    }

    # Command: --run
    if ($FirstArg -eq '--run') {
        $file = $Rest[0]
        if (-not $file -or -not (Test-Path $file)) { Write-Status "Binary not found." "ERROR"; return }
        & $global:RuntimeExe $file
        return
    }

    # Quick-Compile Fallback
    if ($FirstArg -and (Test-Path $FirstArg) -and $FirstArg.EndsWith(".zs")) {
        & $global:CompilerExe $FirstArg
    } 
    else {
        Write-Status "Invalid command. Use 'zs --help'." "ERROR"
    }
}

Write-Status "ZEGA Toolchain v2.0.0.3 Active." "SUCCESS"